name = "TPSAInterface"
uuid = "575459ea-959c-4603-9b15-d63fb6693033"
authors = ["Matt Signorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test"]
