name = "TPSAInterface"
uuid = "575459ea-959c-4603-9b15-d63fb6693033"
authors = ["Matt Signorelli <mgs255@cornell.edu> and contributors"]
version = "0.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"

[extensions]
TPSAInterfaceGTPSAExt = "GTPSA"

[compat]
GTPSA = "1.4"
julia = "1.9"

[extras]
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test", "GTPSA"]
